baseURL = "http://x64.life/"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh-cn"
title = "X64·Life"
copyright = ""
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = ""
enableValine = true

[params.valine]
  appId = 'coqbkGw8l2pi37OMbi1uqybj-MdYXbMMI'
  appKey = 'WWyjHI992u5UmxulDV1MUMeP'
  avator = "mm"

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/post"
name = "Archive"
weight = 1
[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/about"
name = "About"
weight = 4
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 5